// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config"; // Hapus import 'env' yang tidak dipakai

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Gunakan process.env bawaan Node.js agar string .env terbaca sempurna
    url: process.env.DATABASE_URL, 
  },
});